# Generated by curation_concerns:models:install
class FileSet < ActiveFedora::Base
  include ::CurationConcerns::FileSetBehavior
  validates :format, presence: { message: 'Your work must have a file format specified.' }
end
